osx_image: xcode9.2
language: objective-c
cache: cocoapods
script:

- set -o pipefail && xcodebuild test -scheme SPiDSDK -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' | xcpretty
